config/routes.rb
Rails.application.routes.draw do

  root'posts#index'

  resources :posts do
    resources :comments
  end

  get '/signup' => 'registrations#new', as: :signup
  post '/signup' => 'registrations#create'
  get '/signin' => 'authentication#new', as: :signin
  post '/signin' => 'authentication#create'
  get 'signout' => 'authentication#destroy', as: :signout

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if !current_user
      redirect_to signin_path, notice: "You must be signed in to do that."
    end
  end

  helper_method :current_user, :authenticate_user
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:notice] = "Username / Password invalid"
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, :authenticate_user, only: [:new, :create, :edit, :update, :destroy]

  def new
    @comment = @post.comments.new
  end

  def create
    @comment= @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_path(@post)
      flash[:notice] = "Comment succcessfully added."
    else
      render :new
      flash[:notice] = "Comment could not be added."
    end
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def update
    @comment = @post.comments.find(params[:id])
    @comment.update(comment_params)
    if @comment.save
      redirect_to post_path(@post)
      flash[:notice] = "Comment successfully updated."
    else
      render :edit
      flash[:notice] = "Comment could not be updated."
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
    flash[:notice] = "Comment was successfully deleted."
  end

  private
  def comment_params
    params.require(:comment).permit(
      :content,
      :user_id,
      :post_id,
    )
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]


  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
      flash[:notice] = "Post successfully submitted."
    else
      render :new
      flash[:notice] = "Post could not be submitted."
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.save
      redirect_to root_path
      flash[:notice] = "Post successfully updated."
    else
      render :edit
      flash[:notice] = "Post could not be updated."
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
    flash[:notice] = "Post successfully deleted."
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(
      :title,
      :content,
      :user_id,
    )
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]= @user.id
      redirect_to root_path
      flash[:notice] = "Congratulations on registering for gReddit"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<h1>Sign In</h1>

<%= form_tag signin_path do |f| %>

  <div class="well col-md-4">
    <%= email_field_tag :email, nil, placeholder: "E-mail", class: "form-control" %>
    <%= password_field_tag :password, nil,  placeholder: "Password", class: "form-control" %>
    <%= submit_tag "Sign In", class: "btn btn-primary", id: "signin-submit-action" %>
  </div>


<% end %>

app/views/comments/_form.html.erb
<div class="container">
  <%= form_for([@post, @comment], html: {class:"form-horizontal"}) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, placeholder: "Comment", class: "form-control col-md-4" %>
  </div>
  <div class="form-group">
    <%= f.submit id:"submit-comment-action", class: "btn btn-primary"%>
  </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h1>Edit a Comment</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<div class="page-header">
  <h1>Add a Comment</h1>
</div>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">

    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">gReddit</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <%if current_user  %>
              <li><a href = #> Welcome, <%= "#{current_user.username}" %></a></li>
              <li> <%= link_to "Sign Out", signout_path, id: "signout-action" %></li>
            <% else %>
              <li> <%= link_to "Sign Up", signup_path  %></li>
              <li> <%= link_to "Sign In", signin_path, id:"sign-in-form"  %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>


<div class="container">
  <% if notice %>
  <div class="container alert alert-success">
    <%= notice %>
  </div>
  <% end %>
</div>


<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {class: "form-horizontal"}) do |f| %>

  <div class="form-group">
    <%= f.label :title, class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content, class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.text_area :content, class:"form-control" %>
    </div>
  </div>

  <%= f.submit "Submit Post", id: "submit-post-action", class: "btn btn-primary col-md-offset-2" %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="jumbotron">
  <h1> Welcome to gReddit!</h1>
</div>

<h3> Recent Posts</h3>


<% @posts.each do |post| %>
  <div class="well">
    <% if current_user && current_user.id  == post.user_id  %>
      <%= link_to "Edit", edit_post_path(post), class: "pull-right btn btn-default", id: "edit-post-#{post.id}-action" %>
      <%= link_to "Delete",post_path(post), method: :delete, data: {confirm: "Are you sure?"}, class: "pull-right btn btn-default", id: "delete-post-#{post.id}-action" %>
    <% end  %>
    <h4><%=link_to "#{post.title}", post_path(post), id: "show-post-#{post.id}-action" %></h4><%= "posted by #{post.user.username} at #{(post.created_at).strftime("%A %b %d at %H:%M")}" %>
    <p><%= post.content %></p>
  </div>
<% end %>

<%= link_to "Write New Post", new_post_path, class: "btn btn-primary", id: "new-post-action" %>

app/views/posts/new.html.erb
<h1>Write a New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="well">
  <h1><%="#{@post.title}" %></h1>
  <p> <%= "posted by #{@post.user.username} on #{@post.created_at.strftime("%b %d, %Y at %H:%M")}" %></p>
  <p><%="#{@post.content}"%></p>
  <% @post.comments.each do |comment| %>
    <div class="well">
      <p>posted by <%= comment.user.username %> on <%= comment.created_at.strftime("%b %d, %Y at %H:%M") %> </p>
      <%= comment.content %>
      <% if current_user && current_user.id == comment.user_id  %>
        <p><%= link_to "Edit", edit_post_comment_path(@post, comment), id: "edit-comment-#{comment.id}-action" %> | <%= link_to "Delete", post_comment_path(@post, comment), method: :delete, id:"delete-comment-#{comment.id}-action" %></p>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to "Back", :back %> | <%= link_to "Add Comment", new_post_comment_path(@post), id: "add-comment-to-post-#{@post.id}-action" %>